name: Build and Push ACA Scheduled Job Image

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build-template.yml
    permissions:
      contents: read
      packages: write
    with:
      service_name: aca-scheduled-job
      dockerfile: ./advanced/aca-scheduled-job/Dockerfile
      context: ./advanced/aca-scheduled-job
      image_description: AI ABP ACA Scheduled Job Image
    secrets:
      REGISTRY_LOGIN_SERVER: ${{ secrets.REGISTRY_LOGIN_SERVER }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}